"""add_mandatory_channels

Revision ID: e8ce696ed17a
Revises: 20260516_0007
Create Date: 2026-05-30 10:19:41.032872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ce696ed17a'
down_revision: Union[str, None] = '20260516_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandatory_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandatory_channels_channel_id'), 'mandatory_channels', ['channel_id'], unique=True)
    op.drop_constraint(op.f('dice_rolls_discount_code_key'), 'dice_rolls', type_='unique')
    op.drop_index(op.f('ix_dice_rolls_discount_code'), table_name='dice_rolls')
    op.create_index(op.f('ix_dice_rolls_discount_code'), 'dice_rolls', ['discount_code'], unique=True)
    op.drop_constraint(op.f('orders_tracking_code_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=True)
    op.drop_constraint(op.f('payments_order_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.drop_constraint(op.f('referral_rewards_order_id_key'), 'referral_rewards', type_='unique')
    op.drop_constraint(op.f('referral_rewards_referred_user_id_key'), 'referral_rewards', type_='unique')
    op.drop_index(op.f('ix_referral_rewards_order_id'), table_name='referral_rewards')
    op.create_index(op.f('ix_referral_rewards_order_id'), 'referral_rewards', ['order_id'], unique=True)
    op.drop_index(op.f('ix_referral_rewards_referred_user_id'), table_name='referral_rewards')
    op.create_index(op.f('ix_referral_rewards_referred_user_id'), 'referral_rewards', ['referred_user_id'], unique=True)
    op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_constraint(op.f('vpn_services_order_id_key'), 'vpn_services', type_='unique')
    op.drop_index(op.f('ix_vpn_services_order_id'), table_name='vpn_services')
    op.create_index(op.f('ix_vpn_services_order_id'), 'vpn_services', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_services_order_id'), table_name='vpn_services')
    op.create_index(op.f('ix_vpn_services_order_id'), 'vpn_services', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('vpn_services_order_id_key'), 'vpn_services', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=False)
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_referral_rewards_referred_user_id'), table_name='referral_rewards')
    op.create_index(op.f('ix_referral_rewards_referred_user_id'), 'referral_rewards', ['referred_user_id'], unique=False)
    op.drop_index(op.f('ix_referral_rewards_order_id'), table_name='referral_rewards')
    op.create_index(op.f('ix_referral_rewards_order_id'), 'referral_rewards', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('referral_rewards_referred_user_id_key'), 'referral_rewards', ['referred_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('referral_rewards_order_id_key'), 'referral_rewards', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('payments_order_id_key'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=False)
    op.create_unique_constraint(op.f('orders_tracking_code_key'), 'orders', ['tracking_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_dice_rolls_discount_code'), table_name='dice_rolls')
    op.create_index(op.f('ix_dice_rolls_discount_code'), 'dice_rolls', ['discount_code'], unique=False)
    op.create_unique_constraint(op.f('dice_rolls_discount_code_key'), 'dice_rolls', ['discount_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_mandatory_channels_channel_id'), table_name='mandatory_channels')
    op.drop_table('mandatory_channels')
    # ### end Alembic commands ###